### ISSUE TITLE
Error in log from version 2022.4.X

### ISSUE THREAD

**Issue by MuppetOwl** [joggs/home_assistant_ebeco#19]
I get this error on every restart. It started from Home Assistant version 2022.4, I'm still able to control the floor thermostats and appear to be working correct so maybe only a warning/error for now on future changed in Home Assistant? 

```
Error adding entities for domain sensor with platform ebeco
19:10:26 – (ERROR) Sensor - message first occurred at 19:10:26 and shows up 8 times
```

```
Error adding entities for domain sensor with platform ebeco
Error while setting up ebeco platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
```

**Comment by bhr74** [comment]
The relay sensor also stop working for a while ago, somebody else have that problem? Is this related?
Mvh 
Bjørn Henning Rørvik

**Comment by joggs** [comment]
Thanks for noting @MuppetOwl . There are new recommendations how to handle the different entity categories and the old way stopped working with 2022.4, so it need to be fixed.

**Comment by PerfectlyNormal** [comment]
I'll see if I can get some time to look at this this weekend if no one else beats me to it. Should just be some quick changes that are needed
