### ISSUE TITLE
Fix deprecated SUPPORT_ constants

### ISSUE THREAD

**Issue by PerfectlyNormal** [joggs/home_assistant_ebeco#21]
As of Home Assistant Core 2022.5, all `SUPPORT_*` constants are deprecated, each entity platform is providing an `EntityFeature` enum to replace them.

We use a few of those, should hopefully be quick to fix. Might be something we can do to remain backward compatible

https://developers.home-assistant.io/blog/2022/04/02/support-constants-deprecation

**Comment by ExMacro** [comment]
Logs are saying this on every boot. If possible, it would be a nice thing to fix in the near future. Thanks already beforehand @joggs !

L```
ogger: homeassistant.helpers.entity
Source: helpers/entity.py:1520
First occurred: 18:46:56 (3 occurrences)
Last logged: 18:47:42

Entity None (<class 'custom_components.ebeco.climate.EbecoClimateDevice'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE|PRESET_MODE: 17>, please create a bug report at https://github.com/joggs/home_assistant_ebeco/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
```
