### ISSUE TITLE
Adding new thermostats gives Unkown error

### ISSUE THREAD

**Issue by MacMac1** [joggs/home_assistant_ebeco#27]
You can add only one EB-500 thermostat at a time. After adding a thermostat the UI will give you Unknown error and you need to restart the whole HA before adding the next one.
![image](https://github.com/joggs/home_assistant_ebeco/assets/15648113/16eda5be-880a-42e2-8905-ea5ccf45ced5)

**Comment by GlimSo** [comment]
Have the exact same issue.

**Comment by oppigard** [comment]
Same

**Comment by Turbobussi** [comment]
Same here.

**Comment by joggs** [comment]
@PerfectlyNormal . Can you take a look?

**Comment by PerfectlyNormal** [comment]
After restarting, it works to add a new one and the integration works as expected? It's just the initial setup that's wonky?

Is there anything relevant being shown in the logs? Under Settings in the left menu, then System, then Logs.

I only have a single thermostat to test with, so support for multiple is very theoretical from my side. Which means I can't really reproduce the problem and will have to rely on a bit of guesswork

**Comment by velodromen** [comment]
Same issue here. Just installed it and managed to add one unit and then I received the Unknown error when trying to add a second unit. I have five units and I got the error message irregardless of which of the units i picked. Will try the workaround suggested (restart HA to add additional units.)

**Comment by PerfectlyNormal** [comment]
There's potentially a fix in #33 (in 336b264). Stepping through the code took me into some internal HomeAssistant cleanup that threw this error. Renaming a variable (🤦) makes it work better for me, but since I don't have multiple devices available, I can't test it properly yet

**Comment by joggs** [comment]
> There's potentially a fix in #33 (in [336b264](https://github.com/joggs/home_assistant_ebeco/commit/336b264275811e38091e9c10efd4ad924f32884e)). Stepping through the code took me into some internal HomeAssistant cleanup that threw this error. Renaming a variable (🤦) makes it work better for me, but since I don't have multiple devices available, I can't test it properly yet

Great. We'll give it a shot. A new release has been created with these changes
