### ISSUE TITLE
Inegration shows thermostats but no devices or entities

### ISSUE THREAD

**Issue by slowtraintodawn** [joggs/home_assistant_ebeco#28]
Hi,

not sure what I've changed but the integration shows no devices or entities. I can authenticate and enumerate the thermostats and can can add the thermostat to HA but the devices or entities never show up.

I had previously succesfully connected to one thermostat but had problems adding the second so I removed the EBECO integration. This is when the problem started. I've tried reloading, reinstalling (a couple of times, manually and via HACS)

Is there a cache file that I need to delete.

Happy to provide logs (and a coffee once I get it working :) ) 

Cheers,
Paul

<img width="699" alt="EBECO" src="https://github.com/joggs/home_assistant_ebeco/assets/31664622/c074b732-2124-41f4-bd7e-7ac0b8d0a82f">

**Comment by illwillSE** [comment]
Same issue here, I don't know when it stopped working (and I only have one thermostat) but no entities are available anymore.

**Comment by torbenb89** [comment]
I have the issue as well. Could be in connection with updating to Home Assistant 2023.8.0 but I am not completely sure. Anyhow my Ebeco integration is not working anymore.

**Comment by robinostlund** [comment]
Also got this issue while updating today, issue seems that main_temperature_sensor is not supported as an argument anymore. Which is used in entity.py:
```
class EbecoEntity(CoordinatorEntity):
    """Parent class for Ebeco Entities."""

    def __init__(self, instance, device_key, main_sensor):
        """Initialize common aspects of an Ebeco sensor."""
        super().__init__(instance["coordinator"])
        self.async_change = instance["async_change"]
        self.device_key = device_key
        self._attr_device_info = DeviceInfo(
            identifiers={(DOMAIN, device_key)},
            manufacturer="Ebeco",
            main_temperature_sensor=main_sensor,
            name=self._device["displayName"],
            building=self._device["building"]["name"],
            suggested_area="Bathroom",
        )
```
