### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by sveininge79** [joggs/home_assistant_ebeco#39]
Hello.
I have managed to install it in homeassistent. But I cant find anyplace where to login to my ebeco account. 
i cant find any info on how to doing that either . 

Svein Inge

**Comment by joggs** [comment]
Hi,
When you have installed it, you also have to add it from the integrations
page in home assistant.
There you will be able to fill in those details


fre 2 feb. 2024 kl. 00:17 skrev sveininge79 ***@***.***>:
