### ISSUE TITLE
Component fails to load?

### ISSUE THREAD

**Issue by prebbz** [joggs/home_assistant_ebeco#5]
Hi,
This component has suddenly stopped working after a recent home assistant update (v3.2.9)

`home-assistant    | 2021-04-06 11:58:56 ERROR (MainThread) [homeassistant.components.homekit] Failed to create a HomeKit accessory for climate.ovre_badrummet
home-assistant    | Traceback (most recent call last):
home-assistant    |   File "/usr/src/homeassistant/homeassistant/components/homekit/__init__.py", line 566, in add_bridge_accessory
home-assistant    |     acc = get_accessory(self.hass, self.driver, state, aid, conf)
home-assistant    |   File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 195, in get_accessory
home-assistant    |     return TYPES[a_type](hass, driver, name, state.entity_id, aid, config)
home-assistant    |   File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 235, in __init__
home-assistant    |     self._async_update_state(state)
home-assistant    |   File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 459, in _async_update_state
home-assistant    |     homekit_hvac_action = HC_HASS_TO_HOMEKIT_ACTION[hvac_action]
home-assistant    | KeyError: 'heat'
`

I have the latest version of the add-on. Any suggestions?

**Comment by joggs** [comment]
Hi Prebbz!
By looking at the error, the problem seems to be inside the homekit integration as it fails to create an accessory based on the ebeco thermostat type.
I am importing valid thermostat types directly from Home assistant core, which means they are valid and correct types that I am using in my code, so I would suggest that you submit this problem on the github page for homekit and see if they can find anything.

**Comment by prebbz** [comment]
Hi Joggs,

Thanks for the prompt reply. I checked now and it seems it was a non-fatal error as the integration appears again. It had stopped working, but I guess it was the version info that was missing. You can close the issue. Thanks again 

Skickat från min iPhone

**Comment by joggs** [comment]
Great!
